//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerRepair
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Agents 
    {
        public int Agent_Id { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string First_Name { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string Last_Name { get; set; }
        [Required]
        [Display(Name = "Employer ID")]
        public string Employ_Id { get; set; }
        [Required]
        [Display(Name = "Shift Type")]
        public string Shift_Type { get; set; }
        [Required]
        public Nullable<int> SystemsSystem_Id { get; set; }
    
        public virtual Systems System { get; set; }
    }
}
