//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerRepair
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Systems = new HashSet<Systems>();
        }
    
        public int Client_Id { get; set; }
        [Required(ErrorMessage = "You must provide a Name")]
        public string First_Name { get; set; }
        [Required(ErrorMessage = "You must provide a Last Name")]
        public string Last_Name { get; set; }
        [Required(ErrorMessage = "You must provide a Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "You must provide a phone number")]
        [Display(Name = "Home Phone")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public string Company { get; set; }
        public string Mobile { get; set; }
        public string Line_1 { get; set; }
        public string Line_2 { get; set; }
        public string City { get; set; }
        public string Post_Code { get; set; }
        public string Country { get; set; }
        public string Source { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Systems> Systems { get; set; }
    }
}
