//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ComputerRepair
{
    public partial class Inventory
    {
        public int Id { get; set; }
        [Required]
        public string Comp_Name{ get; set; }
        public System.DateTime Comp_Check_In { get; set; }
        public System.DateTime Comp_Check_Out { get; set; }
        public string Brand_Name { get; set; }
        public bool Is_Ram_Installed { get; set; }
        public bool Is_Power_Supply_Installed { get; set; }
        public string Part_Type { get; set; }
        public bool Is_Complete_System { get; set; }
        public string Serial_Number { get; set; }
        public string Service_Number { get; set; }
        public bool Is_Asset_Tags { get; set; }
        public string Asset_ID { get; set; }
        public string Issues_Note { get; set; }
    }
}