//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerRepair
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Systems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Systems()
        {
            this.Agents = new HashSet<Agents>();
        }
    
        public int System_Id { get; set; }
        [Required]
        [Display(Name = "Brand")]
        public string Brands { get; set; }
        public string Note { get; set; }
        [Required]
        [Display(Name = "Drop off Date")]
        public System.DateTime Drop_Off_Date { get; set; }
        [Required]
        [Display(Name = "Pick Up Date")]
        public System.DateTime Pick_Up_Date { get; set; }
        [Required]
        public string Quote { get; set; }
        [Display(Name = "Laptop")]
        public bool IsLaptop { get; set; }
        [Display(Name = "Desktop")]
        public bool IsDesktop { get; set; }
        [Display(Name = "All In One")]
        public bool Is_All_In_One { get; set; }
        [Display(Name = "Monitor")]
        public bool IsMonitor { get; set; }
        [Display(Name = "Tablet")]
        public bool Tablet { get; set; }
        [Display(Name = "Cell Phone")]
        public bool IsCell_Phone { get; set; }
        [Required]
        [Display(Name = "MAC Address")]
        public string Mac_Number { get; set; }
        [Display(Name = "Priority")]
        public string Priority { get; set; }
        [Display(Name = "Priority")]
        public string Currect_Status { get; set; }
        [Display(Name = "Job_Completed")]
        public string Job_Completed { get; set; }
        [Display(Name = "Paid")]
        public bool Paid { get; set; }
        [Display(Name = "Data BackUp Required")]
        public bool Data_BackUp_Required { get; set; }
        [Display(Name = "Login Details")]
        public string Login_Details { get; set; }
        [Display(Name = "Missing Adapter")]
        public bool Missing_Adapter { get; set; }
        [Display(Name = "Missing Keys")]
        public bool Missing_Keys { get; set; }
        [Display(Name = "Broken Screen")]
        public bool Broken_Screen { get; set; }

        public int CustomersClient_Id { get; set; }
    
        public virtual Customers Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agents> Agents { get; set; }
    }
}
