//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerRepair
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Systems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Systems()
        {
            this.Agents = new HashSet<Agents>();
        }
    
        public int System_Id { get; set; }
        [Required]
        [Display(Name = "Brand")]
        public string Brands { get; set; }
        public string Note { get; set; }
        [Required]
        [Display(Name = "Drop off Date")]
        public System.DateTime Drop_Off_Date { get; set; }
        [Required]
        [Display(Name = "Pick Up Date")]
        public System.DateTime Pick_Up_Date { get; set; }
        [Required]
        public string Quote { get; set; }
        public int CustomersClient_Id { get; set; }
    
        public virtual Customers Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agents> Agents { get; set; }
    }
}
